server:
  port: 8091
spring:
  application:
    name: school
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useTimezone=true&serverTimezone=UTC
    username: root
    password: 4MBFdvBrf^gMt*6!
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
